### ISSUE TITLE
Trying to get bow from hex.pm

### ISSUE THREAD

**Issue by AppyCat** [Recruitee/bow#1]
I am trying to get bow from hex.pm, but it says it does not recognize the package.

Could you let me know how to write the code to get it directly from github.

Thanks.

**Comment by achempion** [comment]
Have the same issue. There are no packages named `bow`.

https://hex.pm/packages?_utf8=✓&search=bow&sort=recent_downloads

**Comment by szajbus** [comment]
Finally there https://hex.pm/packages/bow
