### ISSUE TITLE
Bow not on hex.pm and not adequately documented

### ISSUE THREAD

**Issue by AppyCat** [Recruitee/bow#2]
Some hopefully helpful eedback:

1. Bow is not available on hex.pm. I got it using github
2. Adding the following to the photo schema file does not work:

def changeset(photo \\ %__MODULE__{}, params) do
    photo
    |> cast(params, [:photo, :sort_order, :alt_tag, :title, :description, :publish])
    |> Bow.Ecto.cast_uploads(params, [:photo])
    |> Bow.Ecto.validate([:photo])
  end

It doesn't recognize Bow.Ecto. I tried 

use Bow.Ecto

and 

use Bow.Ecto.Schema

I would say this plugin is not adequately documented. If there is a fully working example with Phoenix 1.3, that would be very helpful. Let me know how I can help on that front.

I think it would be awesome to have something as smooth and well documented as Carrierwave in Elixir.

Best documentation is very explicit, nothing implicit for an easier onboarding path for Elixir noobs. Having looked at the code, it does look quite a bit more concise than Arc :)

**Comment by szajbus** [comment]
We're finally on hex.pm and the docs were also improved hopefully since this issue was created.
